### ISSUE TITLE
can I  export  a layer  or several layers to image on layered draw?  

### ISSUE THREAD

**Issue by kitterive** [CanArslanDev/simple_painter#1]
can I  export  a layer  or several layers to image on layered draw?   if could, how to do it? thanks

**Comment by CanArslanDev** [comment]
Hello, first of all thank you for your feedback. Your feedback is very important for me to improve and popularize the package.

Unfortunately, it is not possible to export a layer or a drawing at the moment, in the current version you can only export a whole canvas. But I have noted this feature. I will consider adding it in the next versions.

I will leave the issue as open, I will think about the feature you mentioned and get back to you later on whether I have added it or not.

Thanks

**Comment by CanArslanDev** [comment]
Hello again,
Layers can now be exported!
Please check the layer example in the example folder. I added a button there on how to do it.
Thanks again for your feedback.
Happy coding.
![Ekran Resmi 2024-12-02 18 17 33](https://github.com/user-attachments/assets/ec2e0fc6-1b9e-402b-9793-254d1d6c2ad3)

**Comment by kitterive** [comment]
Thanks , you are effective!
