### ISSUE TITLE
select_image file Null check operator used on a null value

### ISSUE THREAD

**Issue by kitterive** [CanArslanDev/simple_painter#2]
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building FutureBuilder<Uint8List>(dirty, state: _FutureBuilderState<Uint8List>#857ce):
Null check operator used on a null value

The relevant error-causing widget was: 
  FutureBuilder<Uint8List> FutureBuilder:file:///Users/guoxiujiang/mywork/mydev/lucida/lib/screens/function_screens/simple_painter/widgets/select_image.dart:71:12
When the exception was thrown, this was the stack: 
#0      SelectImageDialog.getImage.<anonymous closure> (package:lucida/screens/function_screens/simple_painter/widgets/select_image.dart:86:48)
#1      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:623:55)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5729:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#6      BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#7      BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#14     _invoke (dart:ui/hooks.dart:312:13)
#15     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#16     _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================

**Comment by CanArslanDev** [comment]
Hi, Thank you for your return.
Can you post the code you called so I can understand where the error is?

Thanks

**Comment by kitterive** [comment]
in your example code   select_image.dart, getImage function

  Widget getImage(String imageUrl) {
    return FutureBuilder<Uint8List>(
      future: Future(() async {
        final response = await HttpClient().getUrl(Uri.parse(imageUrl));
        final bytes = await consolidateHttpClientResponseBytes(
          await response.close(),
        );
        final imageUint8List = bytes;
        return imageUint8List;
      }),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          return GestureDetector(
            onTap: () => Navigator.pop(context, snapshot.data),
            child: FractionallySizedBox(
              widthFactor: 1 / 4,
              child: Image.memory(snapshot.data!),
            ),
          );
        } else {
          return const CircularProgressIndicator();
        }
      },
    );
  }
}

**Comment by kitterive** [comment]
I got it , may be your  https://picsum.photos/*  background ,can't get because network

**Comment by CanArslanDev** [comment]
Yes, I noticed the problem, but the problem is not caused by the package, but by the android emulator.
